// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"go-zero-microservice-demo/service/core/service"
	"go-zero-microservice-demo/service/internal/logic"
	"go-zero-microservice-demo/service/internal/svc"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	service.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetToken(ctx context.Context, in *service.GetTokenRequest) (*service.GetTokenResponse, error) {
	l := logic.NewGetTokenLogic(ctx, s.svcCtx)
	return l.GetToken(in)
}

func (s *UserServer) JwtAuth(ctx context.Context, in *service.AuthRequest) (*service.AuthResponse, error) {
	l := logic.NewJwtAuthLogic(ctx, s.svcCtx)
	return l.JwtAuth(in)
}
