// Code generated by goctl. DO NOT EDIT.
package types

type EmptyResponse struct {
}

type GetTokenRequest struct {
	UserId   int    `json:"user_id"`
	UserName string `json:"user_name"`
	GroupId  string `json:"group_id"`
}

type GetTokenResponse struct {
	Token string `json:"token"`
}

type UserInfoRequest struct {
	Token string `json:"token"`
}

type UserInfoResponse struct {
	UserName string `json:"user_ame"`
	GroupId  string `json:"group_id"`
}
